[book]
authors = ["samtaggart"]
language = "en"
multilingual = false
src = "src"
title = "African Regen Futures Handbook"

[output.html]
no-section-label = true

[output.html.print]
enable = false    # include support for printable output
page-break = true # insert page-break after each chapter